### ISSUE TITLE
How do I create an ISLa solver with _no_ constraints?

### ISSUE THREAD

**Issue by andreas-zeller** [rindPHI/isla#40]
In ISLaSolver.__init__(), the values `""` and `None` for `formula` should be accepted as "no constraints". `true` is a workaround.

**Comment by rindPHI** [comment]
@andreas-zeller The `formula` parameter is already optional, you can pass `None` or simply omit it. Do you consider it important to also be able to pass an empty string? If so, why?

**Comment by andreas-zeller** [comment]
My point is that it is easier to guess `None` than `"true"` as a default value :-)  If `None` is an "official" option, I'd suggest to simply reverse the setting – i.e. have `formula=None` as the default value in the function signature and doc, and in the code, have `if formula is None: formula = "true"` or likewise.

**Comment by rindPHI** [comment]
> My point is that it is easier to guess `None` than `"true"` as a default value :-) If `None` is an "official" option, I'd suggest to simply reverse the setting – i.e. have `formula=None` as the default value in the function signature and doc, and in the code, have `if formula is None: formula = "true"` or likewise.

I see, and I'm convinced ;) The linked PR will change that. Your issues will find their way into ISLa 1.10.0.
